### ISSUE TITLE
fix/customer-mypage-edit-update-phone

### ISSUE THREAD

**Issue by hoseong511** [SpringProject24/FoodieTree#110]
마이페이지에서 휴대폰 번호를 수정하는 기능을 수행했을 때, 서버측에서 에러가 발생합니다..!
동적쿼리를 만드는 부분이 이상한거 같은데 한 번 확인해주세요 감사합니다!

> ## TODO
> - fix/customer-mypage-edit-update-phone
> ```
> 2024-07-04 23:30:24.172  INFO 98305 --- [nio-8083-exec-1] o.n.f.d.c.service.CustomerMyPageService  : update type: phone, value: 010-1234-1234
> 2024-07-04 23:30:24.182 DEBUG 98305 --- [nio-8083-exec-1] o.n.f.d.c.m.C.updateCustomerInfo         : ==>  Preparing: UPDATE tbl_customer WHERE customer_id = ?
> 2024-07-04 23:30:24.182 DEBUG 98305 --- [nio-8083-exec-1] o.n.f.d.c.m.C.updateCustomerInfo         : ==> Parameters: hoho12@hoho.com(String)
> 2024-07-04 23:30:24.185  WARN 98305 --- [nio-8083-exec-1] o.m.jdbc.message.server.ErrorPacket      : Error: 1064-42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE customer_id = 'hoho12@hoho.com'' at line 3
> 2024-07-04 23:30:24.212 ERROR 98305 --- [nio-8083-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: 
> ### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: (conn=28805) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE customer_id = 'hoho12@hoho.com'' at line 3
> ### The error may exist in mappers/CustomerMyPageMapper.xml
> ### The error may involve defaultParameterMap
> ### The error occurred while setting parameters
> ### SQL: UPDATE tbl_customer                    WHERE customer_id = ?
> ```
>  

 _Originally posted by @hoseong511 in [#107](https://github.com/SpringProject24/FoodieTree/issues/107#issuecomment-2209168814)_

**Comment by munginisfree** [comment]
넵 확인해보겠습니다

**Comment by munginisfree** [comment]
해결 완료!
