### ISSUE TITLE
fix/email-set-subject

### ISSUE THREAD

**Issue by hoseong511** [SpringProject24/FoodieTree#120]
## Desc
회원가입 시, purpose: signup 을 이용함에도 수신한 메일의 제목이 '비밀번호 재설정 인증 코드' 입니다.
```setSubject``` 에도 분기처리가 필요해보입니다!

## Detail
<img width="982" alt="image" src="https://github.com/SpringProject24/FoodieTree/assets/62678380/d008e3a2-e85a-45ce-8b3d-4bb4de2b3c10">

## Todo
- [x] 메일 제목 분기 처리

**Comment by munginisfree** [comment]
어랏 확인해보겠습니다

**Comment by munginisfree** [comment]
회원가입 인증 코드도 다른 색깔로 변경할까요?
